# https://taskfile.dev/usage/
version: "3"
tasks:
  default: bun run dev
  b: |
    bun vite build --emptyOutDir
  b2: bun run build

  pre: bun run preview

  ## Setup
  setup: |
    bun install

  init: |
    bun create vite slink-collector --template vanilla-ts
    bun add -d @types/chrome tailwindcss postcss autoprefixer daisyui
    bun tailwindcss init --postcss --esm --ts